apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vulnscan-db-auth
  namespace: vulnscan
spec:
  encryptedData:
    DB_PASSWORD: AgB1OzOh6+TKi65+3YBhUc27bOEKkHVRLgsSdi6tl5xtXSdy+k9I99c4yZKgxaen8DS4FrX7Qa1K7U7+8bbLh/l4c/TSU/uGrr7Oz9D1Y7qmAI2lhPFV01ApilN45KwMn4GpdhmrFSkTHu8NyW4UVDBAgZpMb9mCraDKLd5Z/745cvaLGUSYsGd/mYynO/kVVCvk8/GOkw0L8ZdS8asDkUGi+5CXieaIMQFrT4/DmQKuQzpNu3U9DX2rBDZFwRP+eYKvXNRVhKJLV9HA/AiGvtOnRkk/612WYrbMqEQSSeqDKjiTdWZ97CSG6CO6mmVRZPmtMV1YaqXXRNf2B7fG528Ad6+RIyu0NFuqu/xm0noV2leeeqXYNATM+3WibsX3/oAKAghQc/UMq2d4+nI7ZijlI/+qxyM9dYr8C3wZFWNbknxLuIrwl11gwx5OVoF2WBjs/+uA4gIF2o45FftLzG7vQVo/u0SQgszIX4vp9JOLIog3368Xkibyw5YFxY8qpaPPBoGNdITgfi4O7epe2zn3y3iWWJTknLi7HtbtwMUrqyuSM1ZhICdYn4KJBJSnW0iilAxDPUnzcuxDSv0xV6tjlvDRn19yZ+gpe+gWD8hf6BW0FhEXbdaQJP0cJpQlgV3JmU7jq8LzADXgjv77ImXzuCUvBkkZ4xs3/XiQbbFzv4+u4tOcfVlaaCJOn+PYuc9SRYWnH+0DFMgUPy47QAY=
    DB_USER: AgAMQHLlDMZhuCjiGhcHRMvilHEbc3jPUSG6kjldsPsEwOwGsmis+wcgSM5DlPb1XKbq4yeZ/KbxW2wMVw6mFPk/s3n2MEtD54XnLgu+8UCZwwNvir3or4vYzBydrnh+Xox/LhWXoXRr9c/c+3yy/d2vENpoljsLaulqG/t/elaujul1WrnBpLcY89PQ5m74ZCm2BO13jz5AF2XttVtyjph1M/qAJS/hWwCbym35J4fMfZWmsaNsKDqes7u2CPYxaKFfIU+eQVsBaUtE22n2A6xO4wyH1WeDR9idQ4RYwzUU7kRs3j+E+imRmZSKSCydEbF3rWf+A6g9fq60rdWDXfGE8qjSdA7dLVBSbvmU5zIbN1EeWGbjEXT+Oga84wxMJvhN1JNwZAeIoMVaDiuROQZ2LvmFn2Vg8jecGbhqNoCspBSWoD5sejJPZXEOhRpoG2KM2E1wrNvRywwydaAFSqdFOzMS2yBLzIhZIEPb0OT95vjQkD1QmJzzwhFqcKPegaAa5lRlnmimgk6ePDCGHhgQD02e87inT/dsUBC1Etnx34diCBVTMgGZ2lAKOqIO4uvSSD1lNs5DedI8dgPbpL4RMNZLNQSGfDMUr/LrOdtX1sS7J7/5AgIePl+E8F4gbhtLKd02EeYzEWoKajhIIECkIb2waADNlUPRHlSRli3mNu6aazibNWZ+p0fHZ3MTV8BaaFZ08SUJFFljHaViWg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: vulnscan-db-auth
      namespace: vulnscan
    type: Opaque

