apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vulnscan-db-auth
  namespace: vulnscan
spec:
  encryptedData:
    DB_PASSWORD: AgB1OzOh6+TKi65+3YBhUc27bOEKkHVRLgsSdi6tl5xtXSdy+k9I99c4yZKgxaen8DS4FrX7Qa1K7U7+8bbLh/l4c/TSU/uGrr7Oz9D1Y7qmAI2lhPFV01ApilN45KwMn4GpdhmrFSkTHu8NyW4UVDBAgZpMb9mCraDKLd5Z/745cvaLGUSYsGd/mYynO/kVVCvk8/GOkw0L8ZdS8asDkUGi+5CXieaIMQFrT4/DmQKuQzpNu3U9DX2rBDZFwRP+eYKvXNRVhKJLV9HA/AiGvtOnRkk/612WYrbMqEQSSeqDKjiTdWZ97CSG6CO6mmVRZPmtMV1YaqXXRNf2B7fG528Ad6+RIyu0NFuqu/xm0noV2leeeqXYNATM+3WibsX3/oAKAghQc/UMq2d4+nI7ZijlI/+qxyM9dYr8C3wZFWNbknxLuIrwl11gwx5OVoF2WBjs/+uA4gIF2o45FftLzG7vQVo/u0SQgszIX4vp9JOLIog3368Xkibyw5YFxY8qpaPPBoGNdITgfi4O7epe2zn3y3iWWJTknLi7HtbtwMUrqyuSM1ZhICdYn4KJBJSnW0iilAxDPUnzcuxDSv0xV6tjlvDRn19yZ+gpe+gWD8hf6BW0FhEXbdaQJP0cJpQlgV3JmU7jq8LzADXgjv77ImXzuCUvBkkZ4xs3/XiQbbFzv4+u4tOcfVlaaCJOn+PYuc9SRYWnH+0DFMgUPy47QAY=
    DB_USER: AgAMQHLlDMZhuCjiGhcHRMvilHEbc3jPUSG6kjldsPsEwOwGsmis+wcgSM5DlPb1XKbq4yeZ/KbxW2wMVw6mFPk/s3n2MEtD54XnLgu+8UCZwwNvir3or4vYzBydrnh+Xox/LhWXoXRr9c/c+3yy/d2vENpoljsLaulqG/t/elaujul1WrnBpLcY89PQ5m74ZCm2BO13jz5AF2XttVtyjph1M/qAJS/hWwCbym35J4fMfZWmsaNsKDqes7u2CPYxaKFfIU+eQVsBaUtE22n2A6xO4wyH1WeDR9idQ4RYwzUU7kRs3j+E+imRmZSKSCydEbF3rWf+A6g9fq60rdWDXfGE8qjSdA7dLVBSbvmU5zIbN1EeWGbjEXT+Oga84wxMJvhN1JNwZAeIoMVaDiuROQZ2LvmFn2Vg8jecGbhqNoCspBSWoD5sejJPZXEOhRpoG2KM2E1wrNvRywwydaAFSqdFOzMS2yBLzIhZIEPb0OT95vjQkD1QmJzzwhFqcKPegaAa5lRlnmimgk6ePDCGHhgQD02e87inT/dsUBC1Etnx34diCBVTMgGZ2lAKOqIO4uvSSD1lNs5DedI8dgPbpL4RMNZLNQSGfDMUr/LrOdtX1sS7J7/5AgIePl+E8F4gbhtLKd02EeYzEWoKajhIIECkIb2waADNlUPRHlSRli3mNu6aazibNWZ+p0fHZ3MTV8BaaFZ08SUJFFljHaViWg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: vulnscan-db-auth
      namespace: vulnscan
    type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: vulnscan
  name: vulnscan-jobs-config
  labels:
    app: vulnscan
data:
  1-podreader.yaml: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
       namespace: vulnscan
       generateName: vulnscan-podreader-
       labels:
          app: vulnscan-podreader
    spec:
      ttlSecondsAfterFinished: 180
      template:
         metadata:
            labels:
               app: vulnscan-podreader
         spec:
           restartPolicy: OnFailure
           nodeSelector:
             kubernetes.io/arch: "amd64"
           serviceAccountName: vulnscan-serviceaccount
           containers:
           - name: podreader
             image: registry.shaytech.net/vulnscan-podreader:latest
             env:
             - name: DB_HOST
               value: 'postgres.postgres'
             - name: DB_NAME
               value: 'vulnscan'
             - name: DB_USER
               valueFrom:
                 secretKeyRef:
                   name: vulnscan-db-auth
                   key: DB_USER
             - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: vulnscan-db-auth
                   key: DB_PASSWORD
             tty: true
             imagePullPolicy: Always
  2-sbomgen.yaml: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
       namespace: vulnscan
       name: vulnscan-sbomgen
       labels:
          app: vulnscan-sbomgen
    spec:
      ttlSecondsAfterFinished: 180
      template:
         metadata:
            labels:
               app: vulnscan-sbomgen
         spec:
           restartPolicy: OnFailure
           nodeSelector:
             kubernetes.io/arch: "amd64"
           serviceAccountName: vulnscan-serviceaccount
           containers:
           - name: sbomgen
             image: registry.shaytech.net/vulnscan-sbomgen:latest
             env:
             - name: DB_HOST
               value: 'postgres.postgres'
             - name: DB_NAME
               value: 'vulnscan'
             - name: DB_USER
               valueFrom:
                 secretKeyRef:
                   name: vulnscan-db-auth
                   key: DB_USER
             - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: vulnscan-db-auth
                   key: DB_PASSWORD
             tty: true
             imagePullPolicy: Always
             resources:
               requests:
                 memory: 12Gi
               limits:
                 memory: 16Gi
  3-vulngen.yaml: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
       namespace: vulnscan
       name: vulnscan-vulngen
       labels:
          app: vulnscan-vulngen
    spec:
      ttlSecondsAfterFinished: 180
      template:
         metadata:
            labels:
               app: vulnscan-vulngen
         spec:
           restartPolicy: OnFailure
           nodeSelector:
             kubernetes.io/arch: "amd64"
           serviceAccountName: vulnscan-serviceaccount
           containers:
           - name: vulngen
             image: registry.shaytech.net/vulnscan-vulngen:latest
             env:
             - name: DB_HOST
               value: 'postgres.postgres'
             - name: DB_NAME
               value: 'vulnscan'
             - name: DB_USER
               valueFrom:
                 secretKeyRef:
                   name: vulnscan-db-auth
                   key: DB_USER
             - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: vulnscan-db-auth
                   key: DB_PASSWORD
             tty: true
             imagePullPolicy: Always
             resources:
               requests:
                 memory: 3Gi
               limits:
                 memory: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
   namespace: vulnscan
   name: vulnscan-jobrunner
   labels:
      app: vulnscan-jobrunner
spec:
  ttlSecondsAfterFinished: 180
  template:
     metadata:
        labels:
           app: vulnscan-jobrunner
     spec:
       restartPolicy: Never
       nodeSelector:
         kubernetes.io/arch: "amd64"
       volumes:
       - name: vulnscan-jobs-vol
         configMap:
           name: vulnscan-jobs-config
       serviceAccountName: vulnscan-serviceaccount
       containers:
       - name: jobrunner
         image: registry.shaytech.net/jobrunner:latest
         env:
         - name: JOB_DIR
           value: '/jobs'
         - name: JOB_NAMESPACE
           value: 'vulnscan'
         - name: JOB_PROCEED_ON_FAIL
           value: 'FALSE'
         tty: true
         imagePullPolicy: Always
         volumeMounts:
         - name: vulnscan-jobs-vol
           mountPath: "/jobs"
---
