#apiVersion: batch/v1
#kind: Job
apiVersion: apps/v1
kind: Deployment
metadata:
   namespace: vulnscan
   name: vulnscan-podreader
   labels:
      app: vulnscan-podreader
spec:
  selector:
    matchLabels:
       app: vulnscan-podreader
  template:
     metadata:
        labels:
           app: vulnscan-podreader
     spec:
#       restartPolicy: OnFailure
       nodeSelector:
         kubernetes.io/arch: "amd64"
       volumes:
        - name: vulnscan-hostdir
          hostPath:
            path: /data/sdata/k3s/apps/vulnscan/podreader/app
            type: Directory
       serviceAccountName: vulnscan-serviceaccount
       containers:
       - name: podreader
         image: registry.shaytech.net/vulnscan-podreader:latest
         command: ["/bin/bash"]
         args: ["-c", "sleep 5d"]
         env:
         - name: DB_HOST
           value: 'postgres.postgres'
         - name: DB_NAME
           value: 'vulnscan'
         - name: DB_USER
           valueFrom:
             secretKeyRef:
               name: vulnscan-db-auth
               key: DB_USER
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: vulnscan-db-auth
               key: DB_PASSWORD
         tty: true
         imagePullPolicy: Always
         volumeMounts:
         - name: vulnscan-hostdir
           mountPath: /app2

---
