apiVersion: batch/v1
kind: Job
metadata:
   namespace: vulnscan
   generateName: vulnscan-podreader-
   labels:
      app: vulnscan-podreader
spec:
  ttlSecondsAfterFinished: 180
  template:
     metadata:
        labels:
           app: vulnscan-podreader
     spec:
       restartPolicy: OnFailure
       nodeSelector:
         kubernetes.io/arch: "amd64"
       serviceAccountName: vulnscan-serviceaccount
       containers:
       - name: podreader
         image: registry.shaytech.net/vulnscan-podreader:latest
         command: ["/bin/bash"]
         args: ["-c", "sleep 20s"]
         tty: true
         imagePullPolicy: Always
