apiVersion: apps/v1
kind: Deployment
metadata:
   namespace: vulnscan
   name: vulnscan-vulngen
   labels:
      app: vulnscan-vulngen
spec:
  replicas: 1
  selector:
     matchLabels:
        app: vulnscan-vulngen
  template:
     metadata:
        labels:
           app: vulnscan-vulngen
     spec:
       nodeSelector:
         kubernetes.io/arch: "amd64"
       volumes:
        - name: vulnscan-hostdir
          hostPath:
            path: /data/sdata/k3s/apps/vulnscan/vulngen/app
            type: Directory
       serviceAccountName: vulnscan-serviceaccount
       containers:
       - name: vulngen
         image: registry.shaytech.net/vulnscan-vulngen:latest
         env:
         - name: DB_HOST
           value: 'postgres.postgres'
         - name: DB_NAME
           value: 'vulnscan'
         - name: DB_USER
           valueFrom:
             secretKeyRef:
               name: vulnscan-db-auth
               key: DB_USER
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: vulnscan-db-auth
               key: DB_PASSWORD
         - name: REFRESH_ALL
           value: 'true'
         command: ["/bin/bash"]
         args: ["-c", "sleep 5d"]
         tty: true
         imagePullPolicy: Always
         volumeMounts:
         - name: vulnscan-hostdir
           mountPath: /app2
         resources:
           requests:
             memory: 1Gi
           limits:
             memory: 2Gi

---
