apiVersion: batch/v1
kind: Job
metadata:
   namespace: vulnscan
   name: vulnscan-vulngen
   labels:
      app: vulnscan-vulngen
spec:
  template:
     metadata:
        labels:
           app: vulnscan-vulngen
     spec:
       restartPolicy: OnFailure
       serviceAccountName: vulnscan-serviceaccount
       containers:
       - name: vulngen
         image: davideshay/vulnscan-vulngen:latest
         env:
         - name: DB_HOST
           value: 'postgres.postgres'
         - name: DB_NAME
           value: 'vulnscan'
         - name: DB_USER
           valueFrom:
             secretKeyRef:
               name: vulnscan-db-auth
               key: DB_USER
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: vulnscan-db-auth
               key: DB_PASSWORD
         - name: REFRESH_ALL
           value: 'true'
         tty: true
         imagePullPolicy: Always
         resources:
           requests:
             memory: 12Gi
           limits:
             memory: 16Gi

---
