name: build-publish-docker-vulnweb
on:
  push:
    paths:
      - 'vulnweb/**'
defaults:
  run:
    working-directory: vulnweb
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
#      - name: Get latest tag
#        id: vars
#        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Clone repository
        uses: actions/checkout@v2
#        with:
#          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./vulnweb/
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vulnscan-vulnweb:latest

      - name: Sync up docker hub readme
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: davideshay/vulnscan-vulnweb
          readme: README.md
          description: Web UI for VULNSCAN
