name: build-publish-docker-podreader
on:
  push:
    paths:
      - 'podreader/**'
defaults:
  run:
    working-directory: podreader
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
#      - name: Get latest tag
#        id: vars
#        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Clone repository
        uses: actions/checkout@v2
#        with:
#          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./podreader/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vulnscan-podreader:latest
